site_name: DMP
theme: readthedocs
use_directory_urls: false
nav:
  - DMP: index.md
  - ARC: arc.md
copyright: "&copy; 2026 | <a href='https://Bioinformatics.ucalgary.ca/' target='_blank'>Bioinformatics Hub</a> | All Rights Reserved."
